# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\pedro\OneDrive\Desktop\Engenharia de software\Estoque-de-produtos\cadastro.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(663, 515)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Cadadstrar = QtWidgets.QPushButton(self.centralwidget)
        self.Cadadstrar.setGeometry(QtCore.QRect(360, 330, 75, 23))
        self.Cadadstrar.setObjectName("Cadadstrar")
        self.loginCad = QtWidgets.QLineEdit(self.centralwidget)
        self.loginCad.setGeometry(QtCore.QRect(240, 120, 113, 20))
        self.loginCad.setObjectName("loginCad")
        self.senhaCad = QtWidgets.QLineEdit(self.centralwidget)
        self.senhaCad.setGeometry(QtCore.QRect(240, 160, 113, 20))
        self.senhaCad.setObjectName("senhaCad")
        self.nomeCad = QtWidgets.QLineEdit(self.centralwidget)
        self.nomeCad.setGeometry(QtCore.QRect(240, 200, 113, 20))
        self.nomeCad.setObjectName("nomeCad")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 30, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(190, 120, 31, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(190, 160, 31, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(150, 200, 81, 16))
        self.label_4.setObjectName("label_4")
        self.voltar = QtWidgets.QPushButton(self.centralwidget)
        self.voltar.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.voltar.setObjectName("voltar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Cadadstrar.setText(_translate("MainWindow", "Cadastrar"))
        self.label.setText(_translate("MainWindow", "Cadastro"))
        self.label_2.setText(_translate("MainWindow", "Login"))
        self.label_3.setText(_translate("MainWindow", "Senha"))
        self.label_4.setText(_translate("MainWindow", "Nome Completo"))
        self.voltar.setText(_translate("MainWindow", "Voltar"))

        